### PR TITLE
Porting some of my own forms here

### PR DESCRIPTION
**Pull request by VasilisThePikachu**
Seems like this became a new place for "forms" 

May as well commit mine here instead of using hackmd

### CODE REVIEW

**Comment by VasilisThePikachu** [comment]
Feel free to modify these if you like

**Comment by Moomoobeef** [comment]
sorry I only just now noticed your pull request, not sure why I didn't get notified about it. I will have a look at it in a little bit!

**Comment by Moomoobeef** [comment]
there are a few duplicate-ish forms but I really like your header, and a few of these I don't have an equivalent to. So I'll go ahead and merge them

**Comment by VasilisThePikachu** [comment]
> there are a few duplicate-ish forms but I really like your header, and a few of these I don't have an equivalent to. So I'll go ahead and merge them

at the time they did not exist lol

**Pull request merged**
